// Regression guard for the hSigL meson-sector δ-closed-loop collapse
// (BUG_meson_sector_dressed_collapse.md).
//
// The σL (scalar) component of the quark self-energy is projected by the spinor IDENTITY δ[d1,d2],
// so a meson-exchange quark loop threading two pion γ5 vertices is closed by a BARE spinor δ sitting
// INSIDE the Dirac chain: tr(δ · γ5 · S · γ5 · S) = tr(γ5·(γ·l1)·γ5·(γ·p1)) ∝ l1·p1 ≠ 0.
//
// The old orderDiracFacs walked the spinor loop with a DIRECTED forward map; the symmetric external δ
// collided on the shared in/out keys and broke the walk, collapsing the trace to a single γ5 →
// tr(γ5)=0 → the whole diagram vanished (numeric ≈ 0 ≪ FORM). The fixed walk is undirected and closes
// the cycle. This driver cross-checks the numeric kernel (the build-time gamma-trace theorem) against
// the Dense DTensor oracle, which contracts the network entry-for-entry with NO ordering walk and is
// therefore unaffected by the bug. Pre-fix: numeric ≈ 0 ≠ dense. Post-fix: they agree, and the trace
// is non-vanishing (guarding against a silent re-collapse). Generated by gen/gen_sigl_dirac.wls.
#include "Sigl_dirac_dense_kernel.hh" // numeric DTensor oracle   (gen/)
#include "Sigl_dirac_num_kernel.hh"   // numeric kernel           (gen/)

#include <cmath>
#include <cstdio>
#include <random>

// smooth fermion regulator (any consistent RF/RFdot validates the engine cross-check).
struct Reg {
  static double RF(double k2, double p2) { return k2 * std::exp(-p2 / k2); }
  static double RFdot(double k2, double p2) { return 2.0 * (k2 + p2) * std::exp(-p2 / k2); }
  static double RB(double, double) { return 0.0; }
  static double RBdot(double, double) { return 0.0; }
  static double dq2RB(double, double) { return 0.0; }
  static double dq2RF(double, double) { return 0.0; }
};

int main() {
  using Dense = Sigl_dirac_dense<Reg>;
  using Num = Sigl_dirac_num_kernel<Reg>;

  std::mt19937 rng(2024);
  std::uniform_real_distribution<double> ul(0.1, 4.0), uk(0.3, 3.0), uc(-0.99, 0.99);
  double maxDenseNum = 0.0, maxAbs = 0.0;
  const int N = 40000;
  for (int i = 0; i < N; ++i) {
    const double l1 = ul(rng), k = uk(rng), p = ul(rng), cos1 = uc(rng);
    const double de = Dense::kernel(l1, cos1, p, k);
    const double iv = Num::kernel(l1, cos1, p, k);
    maxDenseNum = std::max(maxDenseNum, std::fabs(de - iv) / (1e-300 + std::fabs(iv)));
    maxAbs = std::max(maxAbs, std::fabs(de));
  }

  std::printf("[σL δ-closed meson quark loop — tr(δ·γ5·S·γ5·S), the orderDiracFacs δ-closure guard]\n");
  std::printf("  Dense vs numeric max rel err = %.3e  (numeric = gamma-trace theorem)\n", maxDenseNum);
  std::printf("  max |Dense|             = %.3e  (non-vanishing δ-closed trace ∝ l1·p1)\n", maxAbs);

  // the trace must NOT be identically zero — that is exactly the bug (a collapsed single-γ5 walk).
  const bool ok = maxDenseNum < 1e-11 && maxAbs > 1e-6;
  std::printf("\n%s\n", ok ? "ALL TESTS PASSED" : "TESTS FAILED");
  return ok ? 0 : 1;
}
