// Phase-2 example 3 — gluon <- quark loop -> gluon: FUNDAMENTAL COLOUR via the NUMERIC path.
//
// The gluon self-energy from a quark loop (quark-gluon vertex i*gamma^mu*T^a), traced by NumTracer
// into a Dirac trace, a trivial flavour loop (-> Nf), and a FUNDAMENTAL-colour trace tr(T^a T^b).
// Generated by gen/gen_glu_quark.wls, which forces the numeric backend's fundamental colour through
// the NUMERIC SUNNet path (sun_value_cx, et/inv/col.hpp). This driver checks the numeric kernel
// (numeric colour) against the Dense DTensor oracle — their agreement validates the numeric
// fundamental-colour fold on a real flow (the production escape hatch for a fundamental net too large
// to instantiate as a dense tensor).
#include "Glu_quark_dense_kernel.hh" // numeric DTensor oracle     (gen/)
#include "Glu_quark_num_kernel.hh"   // numeric kernel (numeric colour)  (gen/)

#include <cmath>
#include <cstdio>
#include <random>

struct Reg {
  static double RF(double k2, double p2) { return k2 * std::exp(-p2 / k2); }
  static double RFdot(double k2, double p2) { return 2.0 * (k2 + p2) * std::exp(-p2 / k2); }
  static double RB(double, double) { return 0.0; }
  static double RBdot(double, double) { return 0.0; }
  static double dq2RB(double, double) { return 0.0; }
  static double dq2RF(double, double) { return 0.0; }
};

int main() {
  using Dense = Glu_quark_dense<Reg>;
  using Num = Glu_quark_num_kernel<Reg>;

  std::mt19937 rng(7);
  std::uniform_real_distribution<double> ul(0.1, 4.0), uk(0.3, 3.0), uc(-0.99, 0.99);
  double maxDenseNum = 0.0, maxAbs = 0.0;
  const int N = 40000;
  for (int i = 0; i < N; ++i) {
    const double l1 = ul(rng), k = uk(rng), p = ul(rng), cos1 = uc(rng);
    const double de = Dense::kernel(l1, cos1, p, k);
    const double iv = Num::kernel(l1, cos1, p, k);
    maxDenseNum = std::max(maxDenseNum, std::fabs(de - iv) / (1e-300 + std::fabs(iv)));
    maxAbs = std::max(maxAbs, std::fabs(de));
  }

  std::printf("[gluon <- quark loop -> gluon — fundamental colour tr(T^a T^b)]\n");
  std::printf("  Dense vs numeric      max rel err = %.3e  (numeric colour fold via sun_value_cx)\n", maxDenseNum);
  std::printf("  max |Dense|                       = %.3e\n", maxAbs);

  // numeric path (gamma-trace theorem + numeric colour fold) carries a bit more FP than the dense
  // oracle; use the established invariant-basis tolerance.
  const bool ok = maxDenseNum < 1e-10 && maxAbs > 1e-6;
  std::printf("\n%s\n", ok ? "ALL TESTS PASSED" : "TESTS FAILED");
  return ok ? 0 : 1;
}
