// Phase-2 example 2 — pion <- quark loop -> pion (Yukawa): fundamental flavour + Dirac + colour.
//
// The pion self-energy from a quark loop with the Yukawa coupling h*qbar*i*gamma5*(tau*pi)*q,
// traced by NumTracer in one shot into a Dirac trace, a FUNDAMENTAL-flavour trace tr(tau^a tau^b)
// (SU(2), the 2nd group), and a FUNDAMENTAL-colour trace tr(1)=Nc. Generated by
// gen/gen_pion_quark.wls via hand-rolled diagrammatic rules. This driver cross-checks the numeric
// kernel (the build-time gamma-trace theorem) against the Dense DTensor oracle; their agreement
// validates the fundamental-flavour engine AND the numeric-path Dirac trace on a flow that carries
// colour x flavour x Dirac at once.
#include "Pion_quark_dense_kernel.hh" // numeric DTensor oracle   (gen/)
#include "Pion_quark_num_kernel.hh"   // numeric kernel           (gen/)

#include <cmath>
#include <cstdio>
#include <random>

// smooth fermion regulator (any consistent RF/RFdot validates the engine cross-check).
struct Reg {
  static double RF(double k2, double p2) { return k2 * std::exp(-p2 / k2); }
  static double RFdot(double k2, double p2) { return 2.0 * (k2 + p2) * std::exp(-p2 / k2); }
  static double RB(double, double) { return 0.0; }
  static double RBdot(double, double) { return 0.0; }
  static double dq2RB(double, double) { return 0.0; }
  static double dq2RF(double, double) { return 0.0; }
};

int main() {
  using Dense = Pion_quark_dense<Reg>;
  using Num = Pion_quark_num_kernel<Reg>;

  std::mt19937 rng(2024);
  std::uniform_real_distribution<double> ul(0.1, 4.0), uk(0.3, 3.0), uc(-0.99, 0.99);
  double maxDenseNum = 0.0, maxAbs = 0.0;
  const int N = 40000;
  for (int i = 0; i < N; ++i) {
    const double l1 = ul(rng), k = uk(rng), p = ul(rng), cos1 = uc(rng);
    const double de = Dense::kernel(l1, cos1, p, k);
    const double iv = Num::kernel(l1, cos1, p, k);
    maxDenseNum = std::max(maxDenseNum, std::fabs(de - iv) / (1e-300 + std::fabs(iv)));
    maxAbs = std::max(maxAbs, std::fabs(de));
  }

  std::printf("[pion <- quark loop -> pion (Yukawa) — fundamental flavour x Dirac x colour]\n");
  std::printf("  Dense vs numeric max rel err = %.3e  ((numeric = gamma-trace theorem))\n", maxDenseNum);
  std::printf("  max |Dense|             = %.3e  (non-vanishing trace: 4 gammas via the R_F q-slash)\n", maxAbs);

  // the trace must not be identically zero (would mean the gamma count came out odd).
  const bool ok = maxDenseNum < 1e-11 && maxAbs > 1e-6;
  std::printf("\n%s\n", ok ? "ALL TESTS PASSED" : "TESTS FAILED");
  return ok ? 0 : 1;
}
