(* ::Package:: *)

(* Generated by CMake at configure time and installed beside NumTracer.m.
   Records where the C++ headers were installed, so the "Generate" backend of
   MakeNTKernel can compile the emitted generator (g++ -I ...) when the package
   is loaded from $UserBaseDirectory/Applications instead of the source tree. *)
NumTracer`Private`$NumTracerInstalledIncludeDir = "/home/franz/.local/share/NumTracer/include";
