// GENERATED by gen_first_kernel.cpp — do not edit.
#pragma once
#include <cmath>
namespace numtracer_kernels { namespace step06 {
template<int N> static inline double powr(double x){ double r=1.0; for(int i=0;i<(N<0?-N:N);++i) r*=x; return N<0?1.0/r:r; }
// fundamental-symbol env layout (fill f[i] per call):
//   f[0] = var(3)
//   f[1] = var(1)
static inline constexpr int nenv = 2;
static inline void fill(double *f, [[maybe_unused]] double l1, [[maybe_unused]] double cos1, [[maybe_unused]] double p) {
  f[0] = p;
  f[1] = cos1;
}
static inline double tr0([[maybe_unused]] const double *f) {
  const double s0 = f[1];
  const double s3 = fma(s0, s0, (-1));
  const double s4 = f[0];
  const double s5 = s4*s4;
  const double s6 = s3*s5;
  const double s7 = -s6;
  return s7;
}
}} // namespace numtracer_kernels::step06
