// Trace FUSION of diag-dressed diagrams (kernels generated by tests/gen/gen_diagfuse_numeric.wls).
// Four diagrams sharing a dressing coefficient and an SU(2) flavour loop fuse into ONE trace; each
// fused kernel must equal its reference, which spells the flavour sum as an explicit scalar.
#include "Diagfusepin_num_kernel.hh"
#include "Diagfusepinref_num_kernel.hh"
#include "Diagfusert_num_kernel.hh"
#include "Diagfusertref_num_kernel.hh"

#include <cmath>
#include <cstdio>

int main()
{
  int fails = 0;
  auto check = [&](const char *what, double got, double want) {
    const double err = std::abs(got - want) / std::max(1.0, std::abs(want));
    const bool ok = err < 1e-12;
    std::printf("%s %-22s got % .15e want % .15e\n", ok ? "  ok  " : "FAIL ", what, got, want);
    if (!ok) ++fails;
  };
  auto Z = [](double y) { return 1.0 + y; };
  auto Gu = [](double y) { return 0.4 + y * y; };
  auto Gd = [](double y) { return 1.3 - 0.2 * y; };
  const double pts[][5] = {{0.7, 1.3, 0.35, 0.9, 1.1}, {-1.2, 0.6, -0.8, 0.3, 2.0}};
  for (const auto &x : pts) {
    const double l0 = x[0], l1 = x[1], cos1 = x[2], p0 = x[3], p = x[4];
    using namespace numtracer_kernels;
    check("runtime token", Diagfusert_num_kernel::kernel(l0, l1, cos1, p0, p, Z, Gu, Gd),
          Diagfusertref_num_kernel::kernel(l0, l1, cos1, p0, p, Z, Gu, Gd));
    check("constant pin", Diagfusepin_num_kernel::kernel(l0, l1, cos1, p0, p, Z),
          Diagfusepinref_num_kernel::kernel(l0, l1, cos1, p0, p, Z));
  }
  if (fails) {
    std::printf("%d check(s) FAILED\n", fails);
    return 1;
  }
  std::printf("fused diag-dressed kernels agree with their references\n");
  return 0;
}
