// Codegen gate for the COMPLEX x MULTI-TRACE intersection — the combination tests/gen was blind to.
// Kernel generated by tests/gen/gen_cplxdisc_numeric.wls; read that file for why the fixture is built
// the way it is.
//
// WHAT IS GRADED, and why it is not a hand-derived value.
//
// A disconnected diagram makes the integrand a POLYNOMIAL in the trace tokens (here degree 4), not a
// linear form. MakeNTKernel emits three bodies for a complex flow:
//
//   #if VERDICT == 2  Pure     drop the imaginary coefficients
//   #elif VERDICT == 1 RePart  Re(Σ c·Πtr) via the ntRe/ntIm accessors      <- what this flow uses
//   #else              complex the untouched expression, every multiply done in std::complex
//
// The complex body is correct by construction at ANY token degree, so it is the oracle. RePart is not
// a competing approximation — it is an IDENTITY, the same value rewritten in terms of ntRe/ntIm — so
//
//     kernel<RePart>(x)  ==  real(kernel<complex>(x))
//
// must hold at every point, for every flow, to roundoff. It is not a property of this fixture, which
// is exactly what makes it a good gate: no tolerance tuning, no physics input, nothing to rebaseline.
//
// Before the multilinear fix this failed in two independent ways at once. The header did not compile
// at all (`Coefficient[lin, tsym[t]]` left the other tokens' `Unique["tr$"]` placeholders in the
// coefficient, and they were printed as bare `tr$2994` identifiers); and had it compiled, the value
// was wrong anyway, because each multilinear term was visited once per token it contains and so
// counted two or three times over.
//
// Pure is deliberately NOT graded here. It is a candidate, valid only when the probe certifies it,
// and on this fixture the probe correctly rejects it (verdict 1, not 2) — asserting anything about a
// rejected candidate would be asserting a property of this flow rather than an identity. The Pure
// body's own correctness is covered where it belongs: the generated probe's verdict-2 test now
// evaluates the expression ntPureIntegrand actually emits, instead of a proxy that kept the traces
// complex and therefore certified a body it had never evaluated.
// FORCE the RePart body, rather than taking whatever the shared verdict header happens to say.
// tests/gen/numtrace_verdict.hh holds ONE macro — whichever flow was regenerated last — so a test
// that relied on NT_CPLXDISC_NUM_VERDICT being defined would compile the RePart body only while this
// fixture happened to run last in DEFAULT_FLOWS, and silently fall through to the `#else` complex
// body (comparing it against itself, a permanent false green) the rest of the time. Forcing it makes
// the gate hermetic and independent of flow ordering. Same `#pragma once` mechanism as the oracle TU:
// include the verdict header first so the kernel header's own include of it cannot undo this.
#include "numtrace_verdict.hh"
#undef NT_CPLXDISC_NUM_VERDICT
#define NT_CPLXDISC_NUM_VERDICT 1

#include "Cplxdisc_num_kernel.hh"

#include <cmath>
#include <cstdio>
#include <random>

// defined in compare_cplxdisc_num_oracle.cpp, which compiles the SAME header with the verdict forced
// to 0 so the untouched complex body is the one instantiated there
double cplxdisc_oracle(double l1, double cos1, double cos2, double p);

int main()
{
  using Num = numtracer_kernels::Cplxdisc_num_kernel;

  std::mt19937_64 rng(20260812);
  std::uniform_real_distribution<double> Ul(0.05, 3.0), Uc(-0.999, 0.999);

  // The kernel is a sum of products of independent traces whose summands can nearly cancel, so a
  // pointwise-relative metric blows up at zeros of the sum even under exact agreement. Gate on the
  // max ABSOLUTE error against the kernel's own overall scale, as compare_discdirac_num.cpp does.
  double maxAbsErr = 0, maxAbs = 0;
  for (int i = 0; i < 200000; ++i) {
    const double l1 = Ul(rng), cos1 = Uc(rng), cos2 = Uc(rng), p = Ul(rng);
    const double a = cplxdisc_oracle(l1, cos1, cos2, p);
    const double n = Num::kernel(l1, cos1, cos2, p);
    maxAbsErr = std::max(maxAbsErr, std::fabs(n - a));
    maxAbs = std::max(maxAbs, std::fabs(a));
  }

  const double rel = maxAbsErr / (maxAbs > 0 ? maxAbs : 1.0);
  std::printf("cplxdisc: RePart vs complex   max|err| = %.3e   scale = %.3e   rel = %.3e\n",
              maxAbsErr, maxAbs, rel);

  // A reassociated sum of ~10 products of traces; 1e-12 is roundoff-loose and still ~11 orders below
  // the double-counting error the old linear decomposition produced (which was O(1) relative).
  if (!(maxAbs > 0)) {
    std::printf("FAIL: the oracle is identically zero over the sample - the fixture is degenerate.\n");
    return 1;
  }
  if (!(rel < 1e-12)) {
    std::printf("FAIL: the RePart body does not reproduce real(complex body). This is an identity, so "
                "the re/imaginary projection in CodegenRealProjection.m (ntProjectIntegrand) is wrong.\n");
    return 1;
  }
  std::printf("cplxdisc: OK\n");
  return 0;
}
