// Single-precision codegen gate ("ComputeType" -> "float"). Kernel generated by
// tests/gen/gen_cplxdisc_numeric.wls, from the same ntk as Cplxdisc_num_kernel.
//
// Two things are graded. At compile time: this TU is built with -Wdouble-promotion -Werror, so any
// double type or literal left in the emitted kernel -- which would silently run that arithmetic in
// double -- fails the build. At run time: the float RePart body must reproduce the real part of the
// DOUBLE complex body (the correct-by-construction oracle of compare_cplxdisc_num.cpp) to float
// accuracy.
//
// The verdict is forced to RePart for the same reason as in compare_cplxdisc_num.cpp: the shared
// verdict header holds whichever flow was generated last.
#include "numtrace_verdict.hh"
#undef NT_CPLXDISCF_NUM_VERDICT
#define NT_CPLXDISCF_NUM_VERDICT 1

#include "Cplxdiscf_num_kernel.hh"

#include <cmath>
#include <cstdio>
#include <random>

// defined in compare_cplxdisc_num_oracle.cpp: real part of the double complex body
double cplxdisc_oracle(double l1, double cos1, double cos2, double p);

int main()
{
  using Num = numtracer_kernels::Cplxdiscf_num_kernel;

  std::mt19937_64 rng(20260930);
  std::uniform_real_distribution<float> Ul(0.05f, 3.0f), Uc(-0.999f, 0.999f);

  // Max absolute error against the kernel's overall scale, not pointwise-relative: the sum of
  // products can nearly cancel, and a relative metric would blow up at its zeros.
  double maxAbsErr = 0, maxAbs = 0;
  for (int i = 0; i < 200000; ++i) {
    const float l1 = Ul(rng), cos1 = Uc(rng), cos2 = Uc(rng), p = Ul(rng);
    const double a = cplxdisc_oracle(l1, cos1, cos2, p);
    const float n = Num::kernel(l1, cos1, cos2, p);
    maxAbsErr = std::max(maxAbsErr, std::fabs(static_cast<double>(n) - a));
    maxAbs = std::max(maxAbs, std::fabs(a));
  }

  const double rel = maxAbsErr / (maxAbs > 0 ? maxAbs : 1.0);
  std::printf("cplxdisc float: float RePart vs double complex   max|err| = %.3e   scale = %.3e   rel = %.3e\n",
              maxAbsErr, maxAbs, rel);

  if (!(maxAbs > 0)) {
    std::printf("FAIL: the oracle is identically zero over the sample - the fixture is degenerate.\n");
    return 1;
  }
  // float epsilon is 6e-8; a few hundred roundings stay well below 1e-5, while a wrong literal, a
  // dropped term or a mis-typed trace is O(1e-3) or larger.
  if (!(rel < 1e-5)) {
    std::printf("FAIL: the float kernel does not reproduce the double one to float accuracy.\n");
    return 1;
  }
  std::printf("cplxdisc float: OK\n");
  return 0;
}
