// Dirac self-trace gate (kernels generated by tests/gen/gen_selftrace_numeric.wls): a spinor line
// closed on a single head, as in the chiral condensate tr S(l).
#include "Selftracea_num_kernel.hh"
#include "Selftraceb_num_kernel.hh"

#include <cmath>
#include <cstdio>

int main()
{
  int fails = 0;
  auto check = [&](const char *what, double got, double want) {
    const double err = std::abs(got - want) / std::max(1.0, std::abs(want));
    const bool ok = err < 1e-12;
    std::printf("%s %-28s got % .15e want % .15e\n", ok ? "  ok  " : "FAIL ", what, got, want);
    if (!ok) ++fails;
  };
  auto Mq = [](double y) { return 0.3 + y * y; };
  auto Zq = [](double y) { return 1.0 + y; };
  const double pts[][5] = {{0.7, 1.3, 0.35, 0.9, 1.1}, {-1.2, 0.6, -0.8, 0.3, 2.0}};
  for (const auto &x : pts) {
    const double l0 = x[0], l1 = x[1], cos1 = x[2], p0 = x[3], p = x[4];
    check("Mq tr1 + Zq tr(lslash)", numtracer_kernels::Selftracea_num_kernel::kernel(l0, l1, cos1, p0, p, Mq, Zq),
          4 * Mq(l1));
    check("tr1 tr(lslash pslash)", numtracer_kernels::Selftraceb_num_kernel::kernel(l0, l1, cos1, p0, p),
          16 * (l0 * p0 + l1 * cos1 * p));
  }
  if (fails) {
    std::printf("%d check(s) FAILED\n", fails);
    return 1;
  }
  std::printf("Dirac self-trace kernels agree with the analytic values\n");
  return 0;
}
