// FINITE-DENSITY codegen gate: a Complex nested below a Power, and the two options that exist for it.
//
// The kernel generated by tests/gen/gen_cplxrt_numeric.wls carries a coefficient
//     1 / (l0 + I*muq + Ep)^2
// i.e. the shape a finite-chemical-potential quark propagator has. That is NOT something the
// real/imaginary split can read off: substituting I -> ii and taking Coefficient[.., ii, 0|1] is exact
// only on a polynomial in ii, and on a rational function Mathematica silently power-series expands and
// returns the leading term. Left alone, "tr0"/(a + I b) projects to ntRe["tr0"]/a — muq deleted from
// every propagator, a wrong number that compiles. "ComplexRuntimeProjection" instead keeps the
// coefficient factored and emits ntRe/ntIm around it, deferring that one projection to runtime.
//
// TWO independent things are graded here, both against the same oracle:
//
//   1. RePart  == real(complex)   — the deferral is correct (upstream issue 3).
//   2. RealOutput == real(complex) under verdict 0 — dropping the complex body still selects a body
//      that computes the exact real part (upstream issue 4).
//
// Both are IDENTITIES, not properties of this flow, so they must hold to roundoff at any verdict.
// The untouched complex body is the oracle: it does every complex multiplication in C++, so it is
// correct by construction whatever the coefficient looks like.
//
// This fixture PROBES VERDICT 0 (the imaginary part genuinely survives — that is what a complex
// denominator does), which is why each TU forces the verdict it wants rather than reading the shared
// header. tests/gen/numtrace_verdict.hh holds ONE macro, whichever flow regenerated last, so a test
// that trusted it would silently compare a body against itself whenever this fixture did not run last
// in DEFAULT_FLOWS — a permanent false green. Same `#pragma once` mechanism as the other TUs: include
// the verdict header first so the kernel header's own include of it cannot undo the override.
#include "numtrace_verdict.hh"
#undef NT_CPLXRT_NUM_VERDICT
#define NT_CPLXRT_NUM_VERDICT 1

#include "Cplxrt_num_kernel.hh"

#include <cmath>
#include <cstdio>
#include <random>

// compare_cplxrt_num_oracle.cpp: same header, verdict forced to 0 (untouched complex body).
double cplxrt_oracle(double l0, double l1, double cos1, double p0, double p, double muq, double Ep);
// compare_cplxrt_num_realoutput.cpp: the "RealOutput" -> True kernel, verdict forced to 0.
double cplxrt_realoutput(double l0, double l1, double cos1, double p0, double p, double muq,
                         double Ep);
double cplxrt_endproj(double l0, double l1, double cos1, double p0, double p, double muq, double Ep);

int main()
{
  using Num = numtracer_kernels::Cplxrt_num_kernel;

  std::mt19937_64 rng(20260812);
  // Strictly positive l0/muq/Ep keep the sample away from the pole of the complex denominator, which
  // is also how the generated probe draws them (anything not named cos*/phi* comes from U(0.25,3)).
  std::uniform_real_distribution<double> Ul(0.05, 3.0), Uc(-0.999, 0.999), Ud(0.25, 3.0);

  // Max ABSOLUTE error against the kernel's own overall scale, not a pointwise relative metric: the
  // integrand is a sum whose summands nearly cancel, so a relative metric blows up at its zeros even
  // under exact agreement. Same choice as compare_cplxdisc_num.cpp.
  double errRePart = 0, errRealOut = 0, errEndProj = 0, maxAbs = 0;
  for (int i = 0; i < 200000; ++i) {
    const double l0 = Ud(rng), l1 = Ul(rng), cos1 = Uc(rng), p0 = Ud(rng), p = Ul(rng),
                 muq = Ud(rng), Ep = Ud(rng);
    const double a = cplxrt_oracle(l0, l1, cos1, p0, p, muq, Ep);
    const double n = Num::kernel(l0, l1, cos1, p0, p, muq, Ep);
    const double r = cplxrt_realoutput(l0, l1, cos1, p0, p, muq, Ep);
    const double e = cplxrt_endproj(l0, l1, cos1, p0, p, muq, Ep);
    errRePart = std::max(errRePart, std::fabs(n - a));
    errRealOut = std::max(errRealOut, std::fabs(r - a));
    errEndProj = std::max(errEndProj, std::fabs(e - a));
    maxAbs = std::max(maxAbs, std::fabs(a));
  }

  const double scale = maxAbs > 0 ? maxAbs : 1.0;
  const double relRePart = errRePart / scale, relRealOut = errRealOut / scale,
               relEndProj = errEndProj / scale;
  std::printf("cplxrt: RePart     vs complex   max|err| = %.3e   rel = %.3e\n", errRePart, relRePart);
  std::printf("cplxrt: RealOutput vs complex   max|err| = %.3e   rel = %.3e   scale = %.3e\n",
              errRealOut, relRealOut, maxAbs);
  std::printf("cplxrt: EndProj    vs complex   max|err| = %.3e   rel = %.3e\n", errEndProj, relEndProj);

  if (!(maxAbs > 0)) {
    std::printf("FAIL: the oracle is identically zero over the sample - the fixture is degenerate.\n");
    return 1;
  }
  if (!(relRePart < 1e-12)) {
    std::printf("FAIL: the RePart body does not reproduce real(complex body) on a coefficient with a "
                "complex denominator. Either ComplexRuntimeProjection failed to defer it (so the "
                "imaginary part of the denominator was dropped symbolically) or ntRe/ntIm are being "
                "applied to the wrong subexpression.\n");
    return 1;
  }
  if (!(relRealOut < 1e-12)) {
    std::printf("FAIL: the RealOutput kernel does not reproduce real(complex body) at verdict 0. "
                "Dropping the untouched complex body must leave verdict 0 selecting the exact RePart "
                "body; it is selecting something else.\n");
    return 1;
  }
  if (!(relEndProj < 1e-12)) {
    std::printf("FAIL: the ComplexEndProjection kernel does not reproduce real(complex body). Its single "
                "body must be ntRe of the full complex integrand.\n");
    return 1;
  }
  std::printf("cplxrt: OK\n");
  return 0;
}
