// Codegen gate for FINITE-T SPATIAL VECTORS — FormTracer's `vecs[q, mu]`, and the spatial pslash
// `vecs[q,mu] gamma[mu,d1,d2]` that a finite-T quark line is written with. Validates the numeric
// kernels generated by tests/gen/gen_spatialvec_numeric.wls against a DIRECT ANALYTIC oracle.
//
// A spatial vector is the parent momentum with the temporal (Matsubara) component zeroed:
//   qS = {0, q_1, q_2, q_3}.  Euclidean metric, component 0 = temporal.
// Dirac traces (Euclidean):
//   tr(A̸ B̸)       = 4 (A.B)
//   tr(A̸ B̸ C̸ D̸)   = 4 [ (A.B)(C.D) - (A.C)(B.D) + (A.D)(B.C) ]
// and a dot with ANY barred leg is the spatial dot, since barring is a projection.
//
//   spat2 = tr( p̸S (p-l)̸S )                = 4 [ pS.pS - pS.lS ]
//   mix4  = tr( p̸S l̸ l̸S p̸ )                = 4 [ (pS.lS)^2 - (pS.lS)(p.l) + (pS.pS)(lS.lS) ]
//   cross = tr(p̸S l̸S) tr(p̸ p̸) - 4 sps(p,l) tr(p̸ p̸)   == 0
//   leg   = lS . P_T(p) . lS                = lS.lS - (lS.p)^2/(p.p)
//
// `leg` is the only one that is not a slash. That distinction matters: a slash is emitted as
// slash(Momentum{{{1.0, base}}}) and carries NO frameMask, reading all four env components, whereas an open
// leg is emitted as lvec<id, base, MASK> — mask from the frame, components from the frame spec. Only
// `leg` makes those two agree in anger (here mask = 0b0110, the parent loop's own being 0b0111).
//
// GRADING. spat2/mix4 are non-zero by construction and graded pointwise-relative against the closed
// form. `cross` is a ZERO identity: two roundings of zero always disagree by 100%, so it is graded
// ABSOLUTELY against the scale the other two reach — and only believed once that scale is large,
// since a kernel that traced to nothing would confirm it for free.
//
// propFrameFT(p0,p,l0,l1,cos1):  pp = {p0, p, 0, 0},  ll = {l0, l1*cos1, l1*sqrt(1-cos1^2), 0}.
// p0 and l0 are drawn NONZERO: at p0 = l0 = 0 the spatial and the full vector coincide and every
// statement here would hold for the wrong reason.
#include "SpatialVec_cross_kernel.hh"
#include "SpatialVec_leg_kernel.hh"
#include "SpatialVec_mix4_kernel.hh"
#include "SpatialVec_spat2_kernel.hh"

#include <array>
#include <cmath>
#include <cstdio>
#include <random>

namespace {
using V4 = std::array<double, 4>;
double dot4(const V4 &a, const V4 &b) { return a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3]; }
// spatial dot (components 1..3); component 0 is the temporal/Matsubara direction
double dotS(const V4 &a, const V4 &b) { return a[1] * b[1] + a[2] * b[2] + a[3] * b[3]; }

struct Kin {
  V4 pp, ll;
  Kin(double p0, double p, double l0, double l1, double cos1)
      : pp{p0, p, 0.0, 0.0}, ll{l0, l1 * cos1, l1 * std::sqrt(1.0 - cos1 * cos1), 0.0}
  {
  }
};

// Each oracle returns {value, term scale}. The scale is the sum of the |individual terms| that went
// into the value, and it is what the deviation is graded against — NEVER the value itself. Both
// closed forms are DIFFERENCES that cross zero inside the sampled kinematics (spat2 at pS.pS =
// pS.lS, mix4 at p·l1 = p0·cos1·l0), so a pointwise-relative test reports ~1 there no matter how
// exact the kernel is; it measures the conditioning of the oracle, not the correctness of the
// kernel. In fact the emitted kernel is the better-conditioned of the two — it evaluates mix4 as
// the already-cancelled 4·p·l1·(p·l1 - p0·cos1·l0) — so a term-magnitude scale is also the only
// criterion that does not penalise it for the oracle's own rounding.
struct Graded {
  double value, scale;
};

Graded oracle_spat2(const Kin &K)
{
  const double a = dotS(K.pp, K.pp), b = dotS(K.pp, K.ll);
  return {4.0 * (a - b), 4.0 * (std::fabs(a) + std::fabs(b))};
}

Graded oracle_mix4(const Kin &K)
{
  const double pSlS = dotS(K.pp, K.ll);
  const double t1 = pSlS * pSlS, t2 = pSlS * dot4(K.pp, K.ll),
               t3 = dotS(K.pp, K.pp) * dotS(K.ll, K.ll);
  return {4.0 * (t1 - t2 + t3), 4.0 * (std::fabs(t1) + std::fabs(t2) + std::fabs(t3))};
}

Graded oracle_leg(const Kin &K)
{
  const double lSp = dotS(K.ll, K.pp); // a barred leg makes any dot with it spatial
  const double a = dotS(K.ll, K.ll), b = lSp * lSp / dot4(K.pp, K.pp);
  return {a - b, std::fabs(a) + std::fabs(b)};
}
} // namespace

int main()
{
  using Spat2 = numtracer_kernels::SpatialVec_spat2_kernel;
  using Mix4 = numtracer_kernels::SpatialVec_mix4_kernel;
  using Cross = numtracer_kernels::SpatialVec_cross_kernel;
  using Leg = numtracer_kernels::SpatialVec_leg_kernel;

  std::mt19937_64 rng(90210);
  std::uniform_real_distribution<double> Up(0.05, 3.0), Uc(-0.999, 0.999), Ut(-3.0, 3.0);
  double devSpat2 = 0, devMix4 = 0, devCross = 0, devLeg = 0, scale = 0;
  for (int i = 0; i < 200000; ++i) {
    const double p0 = Ut(rng), p = Up(rng), l0 = Ut(rng), l1 = Up(rng), cos1 = Uc(rng);
    const Kin K(p0, p, l0, l1, cos1);

    const Graded a2 = oracle_spat2(K), a4 = oracle_mix4(K), aL = oracle_leg(K);
    const double n2 = Spat2::kernel(p0, p, l0, l1, cos1);
    const double n4 = Mix4::kernel(p0, p, l0, l1, cos1);
    const double nL = Leg::kernel(p0, p, l0, l1, cos1);
    devSpat2 = std::max(devSpat2, std::fabs(n2 - a2.value) / a2.scale);
    devMix4 = std::max(devMix4, std::fabs(n4 - a4.value) / a4.scale);
    devLeg = std::max(devLeg, std::fabs(nL - aL.value) / aL.scale);

    // the zero identity, graded against the same scale — never against its own (zero) value
    devCross = std::max(devCross, std::fabs(Cross::kernel(p0, p, l0, l1, cos1)) / a4.scale);
    // a kernel that traced to nothing would confirm every statement here for free
    scale = std::max(scale, std::max(std::fabs(a2.value), std::fabs(a4.value)));
  }

  std::printf("spatial-vector codegen numeric vs analytic (deviation / term scale):\n");
  std::printf("  spat2 tr(pS (p-l)S)     dev = %.3e\n", devSpat2);
  std::printf("  mix4  tr(pS l lS p)     dev = %.3e\n", devMix4);
  std::printf("  cross ntSPS vs leaf     dev = %.3e\n", devCross);
  std::printf("  leg   lS.P_T(p).lS      dev = %.3e\n", devLeg);
  std::printf("  non-degeneracy: max |oracle| = %.3e\n", scale);

  const bool ok = devSpat2 < 1e-13 && devMix4 < 1e-13 && devCross < 1e-13 && devLeg < 1e-13 &&
                  scale > 1e-6;
  std::printf(ok ? "ALL TESTS PASSED\n" : "TESTS FAILED\n");
  return ok ? 0 : 1;
}
