// Finite-density COMPLEX-FRAME gate (kernels generated by tests/gen/gen_cplxenv_numeric.wls).
//
// The external quark leg has Euclidean frequency p0 - i muq, so (a) the projector denominator 1/k^2
// of the internal line k = l - p and (b) the dressing atom (l0 + i muq) are complex. Each kernel
// returns Re of its integrand ("ComplexEndProjection"), which depends on the IMAGINARY halves of
// those leaves through the products, and is graded here against a direct std::complex evaluation
// of the same integrand. Kernel (c) pins a complex numeric coefficient inside a Lorentz sum.
// Euclidean conventions: tr[g_mu a g_nu b] = 4 (a_mu b_nu + a_nu b_mu - delta_munu a.b).
#include "Cplxcoef_num_kernel.hh"
#include "Cplxenva_num_kernel.hh"
#include "Cplxenvb_num_kernel.hh"

#include <array>
#include <cmath>
#include <complex>
#include <cstdio>

using C = std::complex<double>;
using V = std::array<C, 4>;

static C dot(const V &a, const V &b)
{
  C s = 0;
  for (int i = 0; i < 4; ++i)
    s += a[i] * b[i];
  return s;
}

static int fails = 0;
static void check(const char *what, double got, double want)
{
  const double err = std::abs(got - want) / std::max(1.0, std::abs(want));
  const bool ok = err < 1e-11;
  std::printf("%s %-34s got % .15e want % .15e (rel %.1e)\n", ok ? "  ok  " : "FAIL ", what, got, want, err);
  if (!ok) ++fails;
}

int main()
{
  const double pts[][6] = {// l0, l1, cos1, p0, p, muq
                           {0.7, 1.3, 0.35, 0.9, 1.1, 0.45},
                           {-1.2, 0.6, -0.8, 0.3, 2.0, 1.7},
                           {0.4, 2.2, 0.1, -0.6, 0.8, 0.0}};
  for (const auto &x : pts) {
    const double l0 = x[0], l1 = x[1], cos1 = x[2], p0 = x[3], p = x[4], muq = x[5];
    // propFrameFT: p = (p0 - i muq, p, 0, 0), l = (l0, l1 cos1, l1 sin1, 0)
    const V P{C(p0, -muq), p, 0, 0}, L{l0, l1 * cos1, l1 * std::sqrt(1 - cos1 * cos1), 0};
    V K;
    for (int i = 0; i < 4; ++i)
      K[i] = L[i] - P[i];
    // (a) tr[g_mu l g_nu p] P^T_munu(k) = 4 [ -l.p - 2 (l.k)(p.k)/k^2 ]
    const C a = 4.0 * (-dot(L, P) - 2.0 * dot(L, K) * dot(P, K) / dot(K, K));
    check("(a) complex 1/k^2", numtracer_kernels::Cplxenva_num_kernel::kernel(l0, l1, cos1, p0, p, muq), a.real());
    // (b) i Zq tr[(lslash + (l0 + i muq))(pslash + 2)] = i Zq (4 l.p + 8 (l0 + i muq)), Zq(l1) = 1 + l1^2
    auto Zq = [](double y) { return 1.0 + y * y; };
    const C b = C(0, 1) * Zq(l1) * (4.0 * dot(L, P) + 8.0 * C(l0, muq));
    check("(b) complex dressing atom", numtracer_kernels::Cplxenvb_num_kernel::kernel(l0, l1, cos1, p0, p, muq, Zq),
          b.real());
  }
  // (c) i tr[ql q1] q2_mu (delta_munu + i q3_mu ql_nu) q1_nu, sp3Frame
  for (const auto &x : {std::array<double, 4>{1.3, 0.35, -0.4, 1.1}, std::array<double, 4>{0.6, -0.7, 0.2, 2.0}}) {
    const double l1 = x[0], cos1 = x[1], cos2 = x[2], p = x[3];
    const double s1 = std::sqrt(1 - cos1 * cos1), s2 = std::sqrt(1 - cos2 * cos2);
    const V q1{p, 0, 0, 0}, q2{-p / 2, p * std::sqrt(3.0) / 2, 0, 0}, q3{-p / 2, -p * std::sqrt(3.0) / 2, 0, 0},
        ql{l1 * cos1, l1 * s1 * cos2, l1 * s1 * s2, 0};
    const C c = C(0, 1) * 4.0 * dot(ql, q1) * (dot(q2, q1) + C(0, 1) * dot(q2, q3) * dot(ql, q1));
    check("(c) complex Lorentz-sum coefficient", numtracer_kernels::Cplxcoef_num_kernel::kernel(l1, cos1, cos2, p),
          c.real());
  }
  if (fails) {
    std::printf("%d check(s) FAILED\n", fails);
    return 1;
  }
  std::printf("complex-frame kernels agree with the direct complex evaluation\n");
  return 0;
}
